package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"text/template"
)

const resetTemplate = `// Code generated by reset generator. DO NOT EDIT.

package {{.Package}}

{{range .Structs}}
func (s *{{.Name}}) Reset() {
	if s == nil {
		return
	}
{{range .Fields}}
	{{.ResetCode}}
{{end}}
}
{{end}}
`

type TemplateData struct {
	Package string
	Structs []StructTemplateData
}

type StructTemplateData struct {
	Name   string
	Fields []FieldTemplateData
}

type FieldTemplateData struct {
	Name      string
	ResetCode string
}

func generateResetFile(pkg *Package) error {
	if len(pkg.Structs) == 0 {
		return nil
	}

	data := &TemplateData{
		Package: pkg.Types.Name(),
		Structs: []StructTemplateData{},
	}

	for _, st := range pkg.Structs {
		structData := StructTemplateData{
			Name:   st.Name,
			Fields: []FieldTemplateData{},
		}

		for _, field := range st.Fields {
			if field.Name == "" || field.Var == nil {
				continue
			}
			fieldData := FieldTemplateData{
				Name:      field.Name,
				ResetCode: generateResetCode(field.Var.Type(), field.Name),
			}
			structData.Fields = append(structData.Fields, fieldData)
		}
		data.Structs = append(data.Structs, structData)
	}

	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	source := buf.Bytes()
	formatted, err := format.Source(source)
	if err != nil {
		return fmt.Errorf("failed to format source: %v\n%s", err, source)
	}

	outputPath := filepath.Join(pkg.Dir, "reset.gen.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return err
	}

	fmt.Printf("Generated: %s\n", outputPath)
	return nil
}

func generateResetCode(t types.Type, fieldName string) string {
	switch u := t.(type) {
	case *types.Basic:
		return fmt.Sprintf("s.%s = %s", fieldName, zeroValue(u.Kind()))

	case *types.Slice:
		return fmt.Sprintf("s.%s = s.%s[:0]", fieldName, fieldName)

	case *types.Map:
		return fmt.Sprintf("clear(s.%s)", fieldName)

	case *types.Pointer:
		elem := u.Elem()
		if hasResetMethod(elem) {
			return fmt.Sprintf(`if s.%s != nil {
		s.%s.Reset()
	}`, fieldName, fieldName)
		}
		if isBasicKind(elem) {
			return fmt.Sprintf(`if s.%s != nil {
		*s.%s = %s
	}`, fieldName, fieldName, zeroValue(elem.Underlying().(*types.Basic).Kind()))
		}
		return fmt.Sprintf("s.%s = nil", fieldName)

	case *types.Named:
		if hasResetMethod(u) {
			return fmt.Sprintf(`if s.%s != nil {
		s.%s.Reset()
	}`, fieldName, fieldName)
		}
		if isBasicKind(u.Underlying()) {
			return fmt.Sprintf("s.%s = %s", fieldName, zeroValue(u.Underlying().(*types.Basic).Kind()))
		}
		return fmt.Sprintf("// TODO: handle named type %s for field %s", u.String(), fieldName)

	case *types.Struct:
		return fmt.Sprintf(`if resetter, ok := s.%s.(interface{ Reset() }); ok {
		resetter.Reset()
	}`, fieldName)

	default:
		return fmt.Sprintf("// TODO: handle type %s for field %s", t.String(), fieldName)
	}
}

func hasResetMethod(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}

	for i := 0; i < named.NumMethods(); i++ {
		method := named.Method(i)
		if method.Name() == "Reset" && method.Signature().Params().Len() == 0 && method.Signature().Results().Len() == 0 {
			return true
		}
	}
	return false
}

func isBasicKind(t types.Type) bool {
	_, ok := t.Underlying().(*types.Basic)
	return ok
}

func zeroValue(kind types.BasicKind) string {
	switch kind {
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
		types.Float32, types.Float64, types.Uintptr:
		return "0"
	case types.Bool:
		return "false"
	case types.String:
		return `""`
	default:
		return "nil"
	}
}
